### ISSUE TITLE
常用代码片段

### ISSUE THREAD

**Issue by thinkerchan** [thinkerchan/blog#30]
## 目录(所有代码自行按需修改)
  - [CSS初始化样式reset.css](#reset)
  - [去除浮动clearfix](#clearfix)
  - [js操作cookie](#js-cookie)
  - [css强制换行/自动换行/强制不换行](#word-wrap)
  - [table边界的样式](#table-border)
  - [js字符串翻转](#js-str-reverse)
  - [js产生随机数字](#js_random_num)
  - [radio-checkbox-select](#radio-checkbox-select)
  - [requestAnimationFrame的兼容性处理](#requestAnimationFrame)
  - [获取鼠标移动的方向](#mouse-enter-leave)
  - [HTML符号转义](#html_escape)
  - [js产生随机字符串](#js_random_string)
  - [解析url中的参数](#parse_url_param)
  - [jQuery回到顶部](#animate_scrolltop)
  - [图片hover放大](#img_hover_bigger)
  - [时间格式化](#time_format)
  - [Object.assign兼容(浅复制)](#assign_polyfill)
  - [JS深复制](#deepclone)
  - [检测是否支持webp](#check_webp)
  - [JSMD5](#jsmd5)
  - [图片转Base64](#img2Base64)
  - [jq jsonp](#jsonp)
  - [控制台获取当前网站用的所有图片资源](#get_pics_url)
  - [常用正则](#reg)

#### <a id="reset" name="reset"> CSS初始化样式reset.css</a>
不同的浏览器对各个标签默认的样式是不一样的，而且有时候我们也不想使用浏览器给出的默认样式，我们就可以用reset.css去掉其默认样式

```css
body, h1, h2, h3, h4, h5, h6, hr, p, blockquote, dl, dt, dd, ul, ol, li, pre, form, fieldset, legend, button, input, textarea, th, td { margin:0; padding:0; }
body, button, input, select, textarea { font:12px/1.5 tahoma, arial, \5b8b\4f53; }
h1, h2, h3, h4, h5, h6{ font-size:100%; }
address, cite, dfn, em, var { font-style:normal; }
code, kbd, pre, samp { font-family:couriernew, courier, monospace; }
small{ font-size:12px; }
ul, ol { list-style:none; }
a { text-decoration:none; }
a:hover { text-decoration:underline; }
sup { vertical-align:text-top; }
sub{ vertical-align:text-bottom; }
legend { color:#000; }
fieldset, img { border:0; }
button, input, select, textarea { font-size:100%; }
table { border-collapse:collapse; border-spacing:0; }
```

#### <a id="clearfix" name="clearfix"> 去除浮动clearfix</a>
通常我们在有浮动元素的情况下，会在同级目录下再创建一个`<div style="clear:both;"></div>`；不过这样会增加很多无用的代码。此时我们用`:after`这个伪元素来解决浮动的问题，如果当前层级有浮动元素，那么在其父级添加上clearfix类即可。
```css
.clearfix:after {
    content: " ";
    display: block;
    visibility: hidden;
    width: 0;
    height: 0;
    clear: both;
    font-size: 0;
    line-height: 0;
    overflow: hidden;
}
.clearfix{zoom:1}
```

#### <a id="js-cookie" name="js-cookie"> js操作cookie</a>

```javascript
  var Cookie = function(name, value, options) {
    var trim = (''.trim || (String.prototype.trim = function () {
          return this.replace(/^\s\s*/, '' ).replace(/\s\s*$/, '' );
        })
    );
    function _trim( text ) {
      return text == null ? "" : text.trim();
    }
    if (typeof value != 'undefined') {
      options = options || {};
      if (value === null) {
        value = '';
        options.expires = -1;
      }
      var expires = '';
      if (options.expires && (typeof options.expires == 'number' || options.expires.toUTCString)) {
        var date;
        if (typeof options.expires == 'number') {
          date = new Date();
          date.setTime(date.getTime() + (options.expires * 24 * 60 * 60 * 1000));
        } else {
          date = options.expires;
        }
        expires = '; expires=' + date.toUTCString();
      }
      var path = options.path ? '; path=' + (options.path) : '';
      var domain = options.domain ? '; domain=' + (options.domain) : '';
      var secure = options.secure ? '; secure' : '';
      document.cookie = [name, '=', encodeURIComponent(value), expires, path, domain, secure].join('');
    } else {
      var cookieValue = null;
      if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';'); // 分割之后形成数组
        for (var i = 0; i < cookies.length; i++) {
          var cookie = _trim(cookies[i]);
          if (cookie.substring(0, name.length + 1) == (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
  };
```

#### <a id="word-wrap" name="word-wrap"> css强制换行/自动换行/强制不换行</a>
```css
/* 强制不换行 */
div{
  white-space:nowrap;
}

/* 自动换行 */
div{
  word-wrap: break-word;
  word-break: normal;
}

/* 强制英文单词断行 */
div{
  word-break:break-all;
}
```

#### <a id="table-border" name="table-border"> table边界的样式</a>
```css
  table {
    border: 1px solid #000;
    padding: 0;
    border-collapse: collapse;
    table-layout: fixed;
    margin-top: 10px;
  }

  table td {
    height: 30px;
    border: 1px solid #000;
    background: #fff;
    font-size: 15px;
    padding: 3px 3px 3px 8px;
    color: #000;
    width: 160px;
  }
```

#### <a id="js-str-reverse" name="js-str-reverse"> js字符串翻转</a>
js中没有直接对字符串进行反转的，需要我们先转换成数组，然后使用数组中的`reverse()`方法翻转，最后在把数组拼接回字符串。
```javascript
var str = "abcdefg";
var revs = str.split("").reverse().join("");
console.log(revs);
```

#### <a id="js_random_num" name="js_random_num"> js产生随机数字</a>
这是利用js里的`Math.random()`产生的。若使用 *1000000 然后再强制转成整型也行；不过使用下面的方式可以更加简洁一些，直接截取随机数的最后6位进行返回：
```javascript
function getRanNum(){
    return (''+Math.random()).slice(-6); // Math.random().toString().slice(-6)
}
```

#### <a id="radio-checkbox-select" name="radio-checkbox-select"> radio-checkbox-select</a>
jquery对radio, checkbox的input标签和select标签的操作

input[type=radio]的操作
```javascript
// boolean, 判断radio是否有被选中的元素
$('#myradio input[type=radio]').is(':checked');

// 设置radio选中某个元素
$('#myradio input:eq(1)').prop('checked', true);

// 设置radio取消选中某个元素
$('#myradio input:eq(1)').prop('checked', false);

// 获取选中的radio的值
var val = $('#myradio input[type=radio]:checked').val();
```

input[type=checkbox]的操作
```javascript
// 判断复选框是否选中
var bool = $('#mycheckbox input[type=checkbox]').is(':checked') ;

// 全选，所有的checkbox都添加上checked属性
$('#checkall').click(function(){
    $('#like input[type=checkbox]').prop('checked', true);
})

// 反选，判断当前的checkbox是否被选中，若被选中则设置checked属性为false，否则设置checked属性为true
$('#reverse').click(function(){
    $('#like input[type=checkbox]').each(function(){
        if($(this).is(':checked')){
            $(this).prop('checked', false);
        }else{
            $(this).prop('checked', true);
        }
    })
})

// 取消选中，去掉所有checkbox的checked属性
$('#deleteall').click(function(){
    $('#like input[type=checkbox]').prop('checked', false);
})

// 获取选中的值
$('#getcheckval').click(function(){
    var result = [];
    $('#mycheckbox input[type=checkbox]:checked').each(function(){
        result.push( $(this).val() );
    })
    console.log(result);
})
```
select标签
```javascript
// 获取select选中的value值，给select一个id，直接使用`val()`获取就行
$('#province').val()
```

#### <a id="radio-checkbox-select" name="requestAnimationFrame"> requestAnimationFrame的兼容性处理</a>
```javascript
// http://paulirish.com/2011/requestanimationframe-for-smart-animating/
// http://my.opera.com/emoller/blog/2011/12/20/requestanimationframe-for-smart-er-animating
// requestAnimationFrame polyfill by Erik Möller. fixes from Paul Irish and Tino Zijdel
// MIT license
(function() {
    var lastTime = 0;
    var vendors = ['ms', 'moz', 'webkit', 'o'];
    for (var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
        window.requestAnimationFrame = window[vendors[x] + 'RequestAnimationFrame'];
        window.cancelAnimationFrame = window[vendors[x] + 'CancelAnimationFrame'] || window[vendors[x] + 'CancelRequestAnimationFrame'];
    }
    if (!window.requestAnimationFrame) window.requestAnimationFrame = function(callback, element) {
        var currTime = new Date().getTime();
        var timeToCall = Math.max(0, 16 - (currTime - lastTime));
        var id = window.setTimeout(function() {
            callback(currTime + timeToCall);
        }, timeToCall);
        lastTime = currTime + timeToCall;
        return id;
    };
    if (!window.cancelAnimationFrame) window.cancelAnimationFrame = function(id) {
        clearTimeout(id);
    };
}());
```

#### <a id="mouse-enter-leave" name="mouse-enter-leave"> 获取鼠标移动的方向</a>
我们一定遇见过鼠标从哪个地方进入到某div中，遮罩就从哪个方向出现，鼠标从哪个地方离开这个div，遮罩就从哪个方向消失。整个动画实现的基础就是获取鼠标移动的方向。

```javascript
/*
 * 获取元素移动的方向
 * @param  $element  元素的jQuery对象
 * @param  event     事件对象
 * @return direction 返回一个数字：0:上，1:右，2:下，3:左
 **/
function getDirection($element, event) {
    var w = $element.width(),
        h = $element.height(),
        x = (event.pageX - $element.offset().left - (w / 2)) * (w > h ? (h / w) : 1),
        y = (event.pageY - $element.offset().top - (h / 2)) * (h > w ? (w / h) : 1),
        direction = Math.round((((Math.atan2(y, x) * (180 / Math.PI)) + 180) / 90) + 3) % 4;

    return direction;
}

$('#content').on('mouseenter', function(event){
    console.log( 'enter: '+ getDirection($(this), event) );
}).on('mouseleave', function(event){
    console.log( 'leave: '+getDirection($(this), event) );
})
```

#### <a id="html_escape" name="html_escape"> HTML符号转义</a>
```javascript
function escapeHTML(text) {
    var replacements= {"<": "&lt;", ">": "&gt;","&": "&amp;", "\"": "&quot;"};
    return text.replace(/[<>&"]/g, function(character) {
        return replacements[character];
    });
}
```

#### <a id="js_random_string" name="js_random_string"> js产生随机字符串</a>
```javascript
Math.random().toString(36).substr(2);
```
很有意思，研究了一下，基本上toString后的参数规定可以是2-36之间的任意整数，不写的话默认是10（也就是十进制），此时返回的值就是那个随机数。

若是偶数，返回的数值字符串都是短的，若是奇数，则返回的将是一个很大长度的表示值。
若<10 则都是数字组成，>10 才会包含字母。
所以如果想得到一长串的随机字符，则需使用一个 > 10 且是奇数的参数，另外根据长度自行使用slice(2,n)截取！

#### <a id="parse_url_param" name="parse_url_param"> 解析url中的参数</a>
用于解析当前URL中带的参数，如 http://www.xiabingbao.com/javascript/2015/01/30/geturl-param/?a=1&b=wenzi

```javascript
  // 解析URL
  function parseURL(url) {
    var a =  document.createElement('a');
    a.href = url;
    return {
      source: url,
      protocol: a.protocol.replace(':',''),
      host: a.hostname,
      port: a.port,
      query: a.search,
      params: (function(){
        var ret = {},
        seg = a.search.replace(/^\?/,'').split('&'),
        len = seg.length, i = 0, s;
        for (;i<len;i++) {
          if (!seg[i]) { continue; }
          s = seg[i].split('=');
          ret[s[0]] = s[1];
        }
        return ret;
      })(),
      file: (a.pathname.match(/\/([^\/?#]+)$/i) || [,''])[1],
      hash: a.hash.replace('#',''),
      path: a.pathname.replace(/^([^\/])/,'/$1'),
      relative: (a.href.match(/tps?:\/\/[^\/]+(.+)/) || [,''])[1],
      segments: a.pathname.replace(/^\//,'').split('/')
    };
  }
```

#### <a id="animate_scrolltop" name="animate_scrolltop"> jQuery回到顶部</a>
回到顶部有不少的方法，没有缓冲效果的话，先在顶部放置一个a标签，然后给回到顶部的链接一个`#`:
```html
// 顶部标签
<a id="top"></a>

// 回到顶部的按钮
<a href="#top">回到顶部</a>
```

如果需要缓冲效果的话，可以使用jQuery中的`animate`:
```javascript
$('body,html').animate({scrollTop:0}, 500);
```

#### <a id="img_hover_bigger" name="img_hover_bigger"> 图片hover放大</a>

```css
a{
  position: relative;
  overflow: hidden;
  display: block;
}
img{
  -webkit-transition: transform .2s ease-out;
    -moz-transition: transform .2s ease-out;
    -ms-transition: transform .2s ease-out;
    -o-transition: transform .2s ease-out;
    transition: transform .2s ease-out;
}
a:hover img{
  -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -ms-transform: scale(1.1);
    -o-transform: scale(1.1);
    transform: scale(1.1);
}
```

```html
<a href="">
  <img src=""  />
</a>
```

#### <a id="time_format" name="time_format"> 时间格式化</a>

```javascript
//格式化日期
Date.prototype.Format = function (fmt) {
  var o = {
    "y+": this.getFullYear(),
    "M+": this.getMonth() + 1,                 //月份
    "d+": this.getDate(),                    //日
    "h+": this.getHours(),                   //小时
    "m+": this.getMinutes(),                 //分
    "s+": this.getSeconds(),                 //秒
    "q+": Math.floor((this.getMonth() + 3) / 3), //季度
    "S+": this.getMilliseconds()             //毫秒
  };
  for (var k in o) {
    if (new RegExp("(" + k + ")").test(fmt)){
      if(k == "y+"){
        fmt = fmt.replace(RegExp.$1, ("" + o[k]).substr(4 - RegExp.$1.length));
      }
      else if(k=="S+"){
        var lens = RegExp.$1.length;
        lens = lens==1?3:lens;
        fmt = fmt.replace(RegExp.$1, ("00" + o[k]).substr(("" + o[k]).length - 1,lens));
      }
      else{
        fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
      }
    }
  }
  return fmt;
}
```
使用：
```javascript
var date = new Date();
console.log(date.Format("yyyy年MM月dd日 hh:mm:ss.S")); //输出: 2016年04月01日 10:41:133
console.log(date.Format("yyyy-MM-dd hh:mm:ss")); //输出: 2016-04-01 10:41:08
console.log(date.Format("yy-MM-dd hh:mm:ss")); //输出: 16-04-01 10:41:08
console.log(date.Format("yy-M-d hh:mm:ss")); //输出: 16-4-1 10:41:08
```

#### <a id="time_format" name="assign_polyfill"> Object.assign兼容(浅复制)</a>

```javascript
if( typeof Object.assign !== 'undefined' ){
  Object.defineProperty(Object, "assign", {
    value: function assign(target, varArgs) {
      'use strict';
      if (target == null) {
        throw new TypeError('Cannot convert undefined or null to object');
      }

      var to = Object(target);

      for (var index = 1; index < arguments.length; index++) {
        var nextSource = arguments[index];

        if (nextSource != null) {
        for (var nextKey in nextSource) {
          if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
          to[nextKey] = nextSource[nextKey];
          }
        }
        }
      }
      return to;
    },
    writable: true,
    configurable: true
    });
}
```
#### <a id="deepclone">深复制</a>
``` js
  var DeepClone = function(obj){
    var tmp ;
    if (obj instanceof Array) {
      tmp = [];
      var len = obj.length;
      for (var i = 0; i < len; i++) {
        tmp[i]=arguments.callee(obj[i]);
      }
      return tmp;
    }
    if (obj instanceof Object) {
      tmp = {};
      var len = obj.length;
      for (var i in obj) {
        tmp[i]=arguments.callee(obj[i]); // 严格模式下不能用callee
      }
      return tmp;
    }
    tmp = obj;
    return tmp;
  }

  // 用法
  var obj = {
    name:'k',
    age:25,
    arr:[1,2,3]
  };

  var _obj = DeepClone(obj);
```

#### <a id="check_webp" name="check_webp"> 检测是否支持webp</a>
``` js
  // 检测是否支持webp
  var isSupportWebp = !![].map && document.createElement('canvas').toDataURL('image/webp').indexOf('data:image/webp')

```
#### <a id="jsmd5">JS MD5</a>
  <a href="./js/MD5.js">MD5.js</a>

#### <a id="img2Base64">Img2Base64</a>
``` js
  var Img2Base64 = function(src){
      function setBase64Image(img) {
          var canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;

          var ctx = canvas.getContext("2d");
          ctx.drawImage(img, 0, 0, img.width, img.height);
          var ext = img.src.substring(img.src.lastIndexOf(".")+1).toLowerCase();
          var dataURL = canvas.toDataURL("image/"+ext);
          return dataURL;
      }
      var image = new Image();
      image.crossOrigin = '';
      image.src = src;
      image.onload = function(){
          var base64 = setBase64Image(image);
          return base64;
      }
  }

```

#### <a id="jsonp"> jq jsonp</a>
``` js
  $.ajax({
    url:url,
    dataType:'jsonp',
    data:{},
    jsonp:'callback',
    jsonpCallbak:'JCB', //缓存接口
    success:function(data) {
      console.log(data)
    }
  });
```

#### <a id="get_pics_url">控制台获取当前网站用的所有图片资源</a>
``` js
  function getImg(){
    var suffix = ['.jpg','.jpeg','.png','.gif'],
      _arr = performance.getEntries(),
      _res=[];
    [].forEach.call(_arr,function(obj){
      if(obj.initiatorType=='img'){
        _res.push(obj.name)
      }
      // initiatorType 并不准, 会把img识别成css
      if(obj.initiatorType=='css'){
        [].forEach.call(suffix,function(suffix){
          if(obj.name.indexOf(suffix)>-1){
            _res.push(obj.name)
          }
        })
      }
    })
    return _res;
  }
```

#### <a id="reg">常用正则</a>
``` js
  var regTool={
    Email : /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,3})$/i,
    Mobile : /^1[34758]\d{9}$/,
    Url: /^(https?):\/\/[^\s&<>#;,"\'\?]+(|#[^\s<>;"\']*|\?[^\s<>;"\']*)$/i,
    Company: /^[\u4e00-\u9fa5a-zA-Z0-9\-\·]+$/,
    OrganizationCode: /^[A-Za-z0-9]{15}$/,
    Name: /^[\u4e00-\u9fa5a-zA-Z]+$/,
    Position: /^[\u4e00-\u9fa5a-zA-Z\-]+$/
  }
```
